apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo
  name: demo
spec:
  containers:
  - image: registry.gitlab.com/netcon2/edgex-data
    name: demo
  restartPolicy: Always
  imagePullSecrets:
     - name: demo
