apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  ports:
  - name: demo
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: demo
  type: NodePort
status:
  loadBalancer: {}
